### ISSUE TITLE
Uncaught Error: Call to a member function get_status() ...

### ISSUE THREAD

**Issue by renanno** [vindi/vindi-woocommerce-subscriptions#41]
Boa tarde

Meu debug.log está apontando seguidamente esse erro:

```
[21-Aug-2017 19:14:37 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_status() on boolean in /home/.../public_html/wp-content/plugins/vindi-woocommerce-subscriptions/includes/class-vindi-webhook-handler.php:185
Stack trace:
#0 /home/.../public_html/wp-content/plugins/vindi-woocommerce-subscriptions/includes/class-vindi-webhook-handler.php(68): Vindi_Webhook_Handler->charge_rejected(Object(stdClass))
#1 /home/.../public_html/wp-content/plugins/vindi-woocommerce-subscriptions/includes/class-vindi-webhook-handler.php(35): Vindi_Webhook_Handler->process_event(Object(stdClass))
#2 /home/.../public_html/wp-includes/class-wp-hook.php(298): Vindi_Webhook_Handler->handle('')
#3 /home/.../public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#4 /home/.../public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /home/.../public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(96): do_action('woocommerce_api...')
#6 /home/.../public_html/wp-includes/cl in /home/.../public_html/wp-content/plugins/vindi-woocommerce-subscriptions/includes/class-vindi-webhook-handler.php on line 185
```

**Comment by lyoncesar** [comment]
Bom dia Renan,
O canal de suporte do plugin é o atendimento@vindi.com.br ou atendimento.vindi.com.br, na opção 'abrir uma solicitação'.
Como este não é o canal de suporte do nosso plugin eu estou encerrando essa issue. Já abri um chamado na nossa central de suporte e um dos nossos analistas entrará em contato com você ainda hoje.

Abraços.
